[project]
name = "flowcore-connector-csv"
version = "0.1.0"
description = "A CSV Source and Destination connector for FlowCore."
authors = [
    { name = "FlowCore Contributors" }
]
dependencies = [
    "flowcore-shared>=1.0.0"
]

[project.entry-points."flowcore.plugins"]
source-csv = "flowcore_connector_csv.source:CsvSourcePlugin"
destination-csv = "flowcore_connector_csv.destination:CsvDestinationPlugin"
