from typing import List, Optional, Protocol, Any
from flowcore_shared.schemas.auth import UserInDB, Organization, Workspace, Role, WorkspaceMember

class UserRepository(Protocol):
    async def create(self, user: UserInDB) -> UserInDB: ...
    async def get(self, user_id: str) -> Optional[UserInDB]: ...
    async def get_by_email(self, email: str) -> Optional[UserInDB]: ...
    async def update(self, user_id: str, updates: dict) -> UserInDB: ...
    async def delete(self, user_id: str) -> bool: ...

class OrganizationRepository(Protocol):
    async def create(self, org: Organization) -> Organization: ...
    async def get(self, org_id: str) -> Optional[Organization]: ...
    async def list_all(self) -> List[Organization]: ...

class WorkspaceRepository(Protocol):
    async def create(self, workspace: Workspace) -> Workspace: ...
    async def get(self, workspace_id: str) -> Optional[Workspace]: ...
    async def get_by_organization(self, org_id: str) -> List[Workspace]: ...
    async def list_all(self) -> List[Workspace]: ...

class RoleRepository(Protocol):
    async def create(self, role: Role) -> Role: ...
    async def get(self, role_id: str) -> Optional[Role]: ...
    async def get_by_name(self, name: str) -> Optional[Role]: ...
    async def list_by_organization(self, org_id: Optional[str]) -> List[Role]: ...

class WorkspaceMemberRepository(Protocol):
    async def add_member(self, member: WorkspaceMember) -> WorkspaceMember: ...
    async def get_member(self, user_id: str, workspace_id: str) -> Optional[WorkspaceMember]: ...
    async def list_by_workspace(self, workspace_id: str) -> List[WorkspaceMember]: ...
    async def list_by_user(self, user_id: str) -> List[WorkspaceMember]: ...
    async def update_role(self, user_id: str, workspace_id: str, role_id: str) -> Optional[WorkspaceMember]: ...
    async def remove_member(self, user_id: str, workspace_id: str) -> bool: ...

class ApiKeyRepository(Protocol):
    async def create(self, workspace_id: str, name: str, key_hash: str, prefix: str, scopes: List[str], created_by: Optional[str]) -> Any: ...
    async def get_by_hash(self, key_hash: str) -> Optional[Any]: ...
    async def list_by_workspace(self, workspace_id: str) -> List[Any]: ...
    async def delete(self, key_id: str, workspace_id: str) -> bool: ...
    async def record_usage(self, key_id: str) -> None: ...

class AuditLogRepository(Protocol):
    async def create(self, entity_id: str, entity_type: str, action: str, details: dict) -> Any: ...
    async def list_by_entity(self, entity_id: str) -> List[Any]: ...
