"""Add execution step schema

Revision ID: 15b1eee23725
Revises: b22ca06c3a84
Create Date: 2026-07-23 21:45:42.190802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '15b1eee23725'
down_revision: Union[str, Sequence[str], None] = 'b22ca06c3a84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('execution_runs', sa.Column('error_message', sa.String(), nullable=True))
    op.add_column('execution_runs', sa.Column('outputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'))
    op.add_column('execution_steps', sa.Column('step_id', sa.String(length=255), nullable=False, server_default='unknown'))
    op.add_column('execution_steps', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('execution_steps', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('execution_steps', sa.Column('retry_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('execution_steps', sa.Column('error_message', sa.String(), nullable=True))
    op.add_column('execution_steps', sa.Column('outputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'))
    op.execute("UPDATE execution_steps SET logs = '[]' WHERE logs IS NULL")
    op.alter_column('execution_steps', 'logs',
               existing_type=sa.VARCHAR(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               postgresql_using='logs::jsonb')
    op.drop_column('execution_steps', 'step_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('execution_steps', sa.Column('step_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.alter_column('execution_steps', 'logs',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(),
               nullable=True)
    op.drop_column('execution_steps', 'outputs')
    op.drop_column('execution_steps', 'error_message')
    op.drop_column('execution_steps', 'retry_count')
    op.drop_column('execution_steps', 'completed_at')
    op.drop_column('execution_steps', 'started_at')
    op.drop_column('execution_steps', 'step_id')
    op.drop_column('execution_runs', 'outputs')
    op.drop_column('execution_runs', 'error_message')
    # ### end Alembic commands ###
