"""Add worker nodes and execution queue fields

Revision ID: 16b0f0969fcb
Revises: d6d0176f89f4
Create Date: 2026-08-14 17:01:05.969529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16b0f0969fcb'
down_revision: Union[str, Sequence[str], None] = 'd6d0176f89f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_nodes',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_run_id', sa.Uuid(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['current_run_id'], ['execution_runs.id'], name=op.f('fk_worker_nodes_current_run_id_execution_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_worker_nodes'))
    )
    op.add_column('execution_runs', sa.Column('attempt_number', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('execution_runs', sa.Column('worker_id', sa.String(length=255), nullable=True))
    op.add_column('execution_runs', sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('execution_runs', sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_execution_runs_worker_id'), 'execution_runs', ['worker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_execution_runs_worker_id'), table_name='execution_runs')
    op.drop_column('execution_runs', 'lease_expires_at')
    op.drop_column('execution_runs', 'claimed_at')
    op.drop_column('execution_runs', 'worker_id')
    op.drop_column('execution_runs', 'attempt_number')
    op.drop_table('worker_nodes')
    # ### end Alembic commands ###
