"""Add workspace and auth models

Revision ID: 49e35a3621ed
Revises: fb2fc623603b
Create Date: 2026-07-24 15:37:53.566412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49e35a3621ed'
down_revision: Union[str, Sequence[str], None] = 'fb2fc623603b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=True)
    op.create_table('permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions'))
    )
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('avatar', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('role_permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_permissions'))
    )
    op.create_index(op.f('ix_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_table('workspaces',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_workspaces_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspaces'))
    )
    op.create_index(op.f('ix_workspaces_name'), 'workspaces', ['name'], unique=False)
    op.create_index(op.f('ix_workspaces_organization_id'), 'workspaces', ['organization_id'], unique=False)
    op.create_table('workspace_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_workspace_members_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_workspace_members_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_workspace_members_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace_members'))
    )
    op.create_index(op.f('ix_workspace_members_role_id'), 'workspace_members', ['role_id'], unique=False)
    op.create_index(op.f('ix_workspace_members_user_id'), 'workspace_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_members_workspace_id'), 'workspace_members', ['workspace_id'], unique=False)
    op.add_column('execution_runs', sa.Column('workspace_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_execution_runs_workspace_id'), 'execution_runs', ['workspace_id'], unique=False)
    op.create_foreign_key(op.f('fk_execution_runs_workspace_id_workspaces'), 'execution_runs', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('execution_steps', sa.Column('workspace_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_execution_steps_workspace_id'), 'execution_steps', ['workspace_id'], unique=False)
    op.create_foreign_key(op.f('fk_execution_steps_workspace_id_workspaces'), 'execution_steps', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('pipeline_versions', sa.Column('workspace_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_pipeline_versions_workspace_id'), 'pipeline_versions', ['workspace_id'], unique=False)
    op.create_foreign_key(op.f('fk_pipeline_versions_workspace_id_workspaces'), 'pipeline_versions', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('pipelines', sa.Column('workspace_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_pipelines_workspace_id'), 'pipelines', ['workspace_id'], unique=False)
    op.create_foreign_key(op.f('fk_pipelines_workspace_id_workspaces'), 'pipelines', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('schedule_run_history', sa.Column('workspace_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_schedule_run_history_workspace_id'), 'schedule_run_history', ['workspace_id'], unique=False)
    op.create_foreign_key(op.f('fk_schedule_run_history_workspace_id_workspaces'), 'schedule_run_history', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('schedules', sa.Column('workspace_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_schedules_workspace_id'), 'schedules', ['workspace_id'], unique=False)
    op.create_foreign_key(op.f('fk_schedules_workspace_id_workspaces'), 'schedules', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    
    # Custom Data Migration
    op.execute("""
        INSERT INTO organizations (id, name, description, created_at, updated_at) 
        VALUES (CAST('00000000-0000-0000-0000-000000000001' AS UUID), 'Default Organization', 'The primary organization', NOW(), NOW())
        ON CONFLICT (name) DO NOTHING;
    """)
    op.execute("""
        INSERT INTO workspaces (id, organization_id, name, description, created_at, updated_at) 
        VALUES (CAST('00000000-0000-0000-0000-000000000002' AS UUID), CAST('00000000-0000-0000-0000-000000000001' AS UUID), 'Default Workspace', 'The default workspace', NOW(), NOW())
        ON CONFLICT (id) DO NOTHING;
    """)

    for table in ['pipelines', 'pipeline_versions', 'execution_runs', 'execution_steps', 'schedules', 'schedule_run_history']:
        op.execute(f"UPDATE {table} SET workspace_id = CAST('00000000-0000-0000-0000-000000000002' AS UUID)")
        op.alter_column(table, 'workspace_id', existing_type=sa.Uuid(), nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_schedules_workspace_id_workspaces'), 'schedules', type_='foreignkey')
    op.drop_index(op.f('ix_schedules_workspace_id'), table_name='schedules')
    op.drop_column('schedules', 'workspace_id')
    op.drop_constraint(op.f('fk_schedule_run_history_workspace_id_workspaces'), 'schedule_run_history', type_='foreignkey')
    op.drop_index(op.f('ix_schedule_run_history_workspace_id'), table_name='schedule_run_history')
    op.drop_column('schedule_run_history', 'workspace_id')
    op.drop_constraint(op.f('fk_pipelines_workspace_id_workspaces'), 'pipelines', type_='foreignkey')
    op.drop_index(op.f('ix_pipelines_workspace_id'), table_name='pipelines')
    op.drop_column('pipelines', 'workspace_id')
    op.drop_constraint(op.f('fk_pipeline_versions_workspace_id_workspaces'), 'pipeline_versions', type_='foreignkey')
    op.drop_index(op.f('ix_pipeline_versions_workspace_id'), table_name='pipeline_versions')
    op.drop_column('pipeline_versions', 'workspace_id')
    op.drop_constraint(op.f('fk_execution_steps_workspace_id_workspaces'), 'execution_steps', type_='foreignkey')
    op.drop_index(op.f('ix_execution_steps_workspace_id'), table_name='execution_steps')
    op.drop_column('execution_steps', 'workspace_id')
    op.drop_constraint(op.f('fk_execution_runs_workspace_id_workspaces'), 'execution_runs', type_='foreignkey')
    op.drop_index(op.f('ix_execution_runs_workspace_id'), table_name='execution_runs')
    op.drop_column('execution_runs', 'workspace_id')
    op.drop_index(op.f('ix_workspace_members_workspace_id'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_user_id'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_role_id'), table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_index(op.f('ix_workspaces_organization_id'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_name'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_permission_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
