"""Add Environment Profiles

Revision ID: 4b84f82a7e30
Revises: 49e35a3621ed
Create Date: 2026-07-24 16:36:28.072541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b84f82a7e30'
down_revision: Union[str, Sequence[str], None] = '49e35a3621ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_environments_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_environments'))
    )
    op.create_index(op.f('ix_environments_workspace_id'), 'environments', ['workspace_id'], unique=False)
    op.create_table('environment_variables',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('environment_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('encrypted_value', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], name=op.f('fk_environment_variables_environment_id_environments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_environment_variables'))
    )
    op.create_index(op.f('ix_environment_variables_environment_id'), 'environment_variables', ['environment_id'], unique=False)
    op.create_index(op.f('ix_environment_variables_key'), 'environment_variables', ['key'], unique=False)
    op.create_table('pipeline_environment_bindings',
    sa.Column('pipeline_id', sa.Uuid(), nullable=False),
    sa.Column('environment_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], name=op.f('fk_pipeline_environment_bindings_environment_id_environments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], name=op.f('fk_pipeline_environment_bindings_pipeline_id_pipelines'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pipeline_id', 'environment_id', name=op.f('pk_pipeline_environment_bindings'))
    )
    op.alter_column('execution_runs', 'workspace_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('execution_steps', 'workspace_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('pipeline_versions', 'workspace_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('pipelines', 'workspace_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('schedule_run_history', 'workspace_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('schedules', 'workspace_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedules', 'workspace_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('schedule_run_history', 'workspace_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('pipelines', 'workspace_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('pipeline_versions', 'workspace_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('execution_steps', 'workspace_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('execution_runs', 'workspace_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_table('pipeline_environment_bindings')
    op.drop_index(op.f('ix_environment_variables_key'), table_name='environment_variables')
    op.drop_index(op.f('ix_environment_variables_environment_id'), table_name='environment_variables')
    op.drop_table('environment_variables')
    op.drop_index(op.f('ix_environments_workspace_id'), table_name='environments')
    op.drop_table('environments')
    # ### end Alembic commands ###
