"""add_owner_tags_to_pipeline

Revision ID: 55d6d92df74c
Revises: a4f1b4133d83
Create Date: 2026-07-20 21:08:42.097746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55d6d92df74c'
down_revision: Union[str, Sequence[str], None] = 'a4f1b4133d83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipelines', sa.Column('owner', sa.String(length=255), nullable=False))
    op.add_column('pipelines', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipelines', 'tags')
    op.drop_column('pipelines', 'owner')
    # ### end Alembic commands ###
