"""M18 Production Reliability models

Revision ID: d6d0176f89f4
Revises: 66c40e519e9c
Create Date: 2026-08-14 00:35:30.881155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6d0176f89f4'
down_revision: Union[str, Sequence[str], None] = '66c40e519e9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_triggers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('pipeline_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('secret_key_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], name=op.f('fk_webhook_triggers_pipeline_id_pipelines'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_webhook_triggers_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_triggers'))
    )
    op.create_index(op.f('ix_webhook_triggers_pipeline_id'), 'webhook_triggers', ['pipeline_id'], unique=False)
    op.create_index(op.f('ix_webhook_triggers_workspace_id'), 'webhook_triggers', ['workspace_id'], unique=False)
    op.create_table('execution_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('step_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('error_category', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['step_id'], ['execution_steps.id'], name=op.f('fk_execution_attempts_step_id_execution_steps'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_execution_attempts_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_attempts'))
    )
    op.create_index(op.f('ix_execution_attempts_step_id'), 'execution_attempts', ['step_id'], unique=False)
    op.create_index(op.f('ix_execution_attempts_workspace_id'), 'execution_attempts', ['workspace_id'], unique=False)
    op.add_column('execution_runs', sa.Column('trigger_context', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('execution_steps', sa.Column('duration_ms', sa.Float(), nullable=True))
    op.add_column('pipelines', sa.Column('concurrency_policy', sa.String(length=50), server_default='ALLOW', nullable=False))
    op.add_column('workspaces', sa.Column('max_concurrent_runs', sa.Integer(), server_default='10', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'max_concurrent_runs')
    op.drop_column('pipelines', 'concurrency_policy')
    op.drop_column('execution_steps', 'duration_ms')
    op.drop_column('execution_runs', 'trigger_context')
    op.drop_index(op.f('ix_execution_attempts_workspace_id'), table_name='execution_attempts')
    op.drop_index(op.f('ix_execution_attempts_step_id'), table_name='execution_attempts')
    op.drop_table('execution_attempts')
    op.drop_index(op.f('ix_webhook_triggers_workspace_id'), table_name='webhook_triggers')
    op.drop_index(op.f('ix_webhook_triggers_pipeline_id'), table_name='webhook_triggers')
    op.drop_table('webhook_triggers')
    # ### end Alembic commands ###
