"""Add workspace models

Revision ID: d8e5538e5f1e
Revises: f99695a937b0
Create Date: 2026-08-02 23:15:32.277707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8e5538e5f1e'
down_revision: Union[str, Sequence[str], None] = 'f99695a937b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_workspace_settings',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('preferred_view', sa.String(length=50), nullable=False),
    sa.Column('default_sort', sa.String(length=50), nullable=False),
    sa.Column('sidebar_collapsed', sa.Boolean(), nullable=False),
    sa.Column('expanded_folders', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_workspace_settings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_workspace_settings'))
    )
    op.create_table('folders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['folders.id'], name=op.f('fk_folders_parent_id_folders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_folders_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_folders'))
    )
    op.create_index(op.f('ix_folders_parent_id'), 'folders', ['parent_id'], unique=False)
    op.create_index(op.f('ix_folders_workspace_id'), 'folders', ['workspace_id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_tags_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags'))
    )
    op.create_index(op.f('ix_tags_workspace_id'), 'tags', ['workspace_id'], unique=False)
    op.create_table('pipeline_tags',
    sa.Column('pipeline_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], name=op.f('fk_pipeline_tags_pipeline_id_pipelines'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_pipeline_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pipeline_id', 'tag_id', name=op.f('pk_pipeline_tags'))
    )
    op.create_table('user_pipeline_favorites',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('pipeline_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], name=op.f('fk_user_pipeline_favorites_pipeline_id_pipelines'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_pipeline_favorites_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'pipeline_id', name=op.f('pk_user_pipeline_favorites'))
    )
    op.create_table('user_recent_pipelines',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('pipeline_id', sa.Uuid(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], name=op.f('fk_user_recent_pipelines_pipeline_id_pipelines'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_recent_pipelines_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'pipeline_id', name=op.f('pk_user_recent_pipelines'))
    )
    op.add_column('pipelines', sa.Column('folder_id', sa.Uuid(), nullable=True))
    op.add_column('pipelines', sa.Column('icon', sa.String(length=100), nullable=True))
    op.add_column('pipelines', sa.Column('color', sa.String(length=50), nullable=True))
    op.add_column('pipelines', sa.Column('is_archived', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index(op.f('ix_pipelines_folder_id'), 'pipelines', ['folder_id'], unique=False)
    op.create_foreign_key(op.f('fk_pipelines_folder_id_folders'), 'pipelines', 'folders', ['folder_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_pipelines_folder_id_folders'), 'pipelines', type_='foreignkey')
    op.drop_index(op.f('ix_pipelines_folder_id'), table_name='pipelines')
    op.drop_column('pipelines', 'is_archived')
    op.drop_column('pipelines', 'color')
    op.drop_column('pipelines', 'icon')
    op.drop_column('pipelines', 'folder_id')
    op.drop_table('user_recent_pipelines')
    op.drop_table('user_pipeline_favorites')
    op.drop_table('pipeline_tags')
    op.drop_index(op.f('ix_tags_workspace_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_folders_workspace_id'), table_name='folders')
    op.drop_index(op.f('ix_folders_parent_id'), table_name='folders')
    op.drop_table('folders')
    op.drop_table('user_workspace_settings')
    # ### end Alembic commands ###
