"""Add schedule features

Revision ID: fb2fc623603b
Revises: 285130a8d40c
Create Date: 2026-07-24 01:08:55.180524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb2fc623603b'
down_revision: Union[str, Sequence[str], None] = '285130a8d40c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('max_retries', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('schedules', sa.Column('retry_delay_seconds', sa.Integer(), nullable=False, server_default='300'))
    op.add_column('schedules', sa.Column('holiday_calendar', sa.String(length=50), nullable=True))
    op.add_column('schedules', sa.Column('blackout_windows', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'blackout_windows')
    op.drop_column('schedules', 'holiday_calendar')
    op.drop_column('schedules', 'retry_delay_seconds')
    op.drop_column('schedules', 'max_retries')
    # ### end Alembic commands ###
