
version: '1.0'
pipeline:
  name: customer_etl
  description: Extract and load customers
  owner: test_owner
steps:
  - step_id: extract_customers
    name: Extract Customers
    connector_id: console
    parameters:
      message: extracting
