import typer
from typing import Optional
from pathlib import Path
from flowcore.sdk.core import FlowCore

app = typer.Typer(help="FlowCore Enterprise ETL CLI", add_completion=False)

@app.command()
def init(
    project_dir: Path = typer.Argument(".", help="Directory to initialize"),
):
    """Initialize a new FlowCore project."""
    typer.echo(f"Initializing FlowCore project in {project_dir}")
    project_dir.mkdir(parents=True, exist_ok=True)
    
    (project_dir / "pipelines").mkdir(exist_ok=True)
    (project_dir / "plugins").mkdir(exist_ok=True)
    (project_dir / "configs").mkdir(exist_ok=True)
    
    (project_dir / ".env").touch()
    
    with open(project_dir / "flowcore.yaml", "w") as f:
        f.write("version: 1.0\nname: my_flowcore_project\n")
        
    with open(project_dir / "README.md", "w") as f:
        f.write("# FlowCore Project\n\nGenerated by FlowCore CLI.\n")
        
    typer.echo(typer.style("[OK] Project initialized successfully.", fg=typer.colors.GREEN))

@app.command()
def run(
    pipeline_file: Path = typer.Argument(..., help="Path to pipeline YAML file"),
):
    """Execute a pipeline."""
    fc = FlowCore()
    try:
        fc.run(str(pipeline_file))
    except Exception as e:
        typer.echo(typer.style(f"Error executing pipeline: {e}", fg=typer.colors.RED))
        raise typer.Exit(code=1)

@app.command()
def validate(
    pipeline_file: Path = typer.Argument(..., help="Path to pipeline YAML file"),
):
    """Validate a pipeline without executing."""
    fc = FlowCore()
    try:
        fc.validate(str(pipeline_file))
        typer.echo(typer.style("[OK] Pipeline validated successfully.", fg=typer.colors.GREEN))
    except Exception as e:
        typer.echo(typer.style(f"Validation failed: {e}", fg=typer.colors.RED))
        raise typer.Exit(code=1)

@app.command()
def doctor():
    """Check environment for potential issues."""
    import sys
    typer.echo("Running diagnostics...")
    typer.echo(f"Python version: {sys.version.split(' ')[0]}")
    typer.echo(typer.style("[OK] Environment looks good.", fg=typer.colors.GREEN))

@app.command()
def version():
    """Show FlowCore version."""
    # TODO: Fetch dynamically
    typer.echo("FlowCore version 1.0.0")

if __name__ == "__main__":
    app()
