from typing import Any, Dict
from pydantic import BaseModel, Field

class RFC7807Error(BaseModel):
    type: str = Field(..., description="A URI reference that identifies the problem type.")
    title: str = Field(..., description="A short, human-readable summary of the problem type.")
    status: int = Field(..., description="The HTTP status code generated by the origin server for this occurrence of the problem.")
    flowcore_code: str = Field(..., description="A stable FlowCore-specific error code.")
    detail: str = Field(..., description="A human-readable explanation specific to this occurrence of the problem.")
    instance: str = Field(..., description="A URI reference that identifies the specific occurrence of the problem.")
